#ifndef __WebLogin__
#define __WebLogin__

/**
@file
Subclass of WebLoginBase, which is generated by wxFormBuilder.
*/

#include "GUIFrame.h"

//// end generated include

/** Implementing WebLoginBase */
class WebLogin : public WebLoginBase
{
	protected:
		// Handlers for WebLoginBase events.
		void OnBtnLogin( wxCommandEvent& event );
	public:
		/** Constructor */
		WebLogin( wxWindow* parent );
	//// end generated class members
        wxString GetUser();
        wxString GetPass();

};

#endif // __WebLogin__
